export const testData = [
    {name: "beet", color: "red", type:"vegetable", eaten:"cooked", part:"root"},
    {name: "carrot", color: "orange", type:"vegetable", eaten:"raw", part:"root"},
    {name: "lettuce", color: "green", type:"vegetable", eaten:"raw", part:"leaf"},
    {name: "apple", color: "red", type:"fruit", eaten:"raw", part:"fruit"},
    {name: "banana", color: "yellow", type:"fruit", eaten:"raw", part:"fruit"},
    {name: "grape", color: "purple", type:"fruit", eaten:"raw", part:"fruit"},
    {name: "potato", color: "brown", type:"vegetable", eaten:"cooked", part:"root"},
    {name: "strawberry", color: "red", type:"fruit", eaten:"raw", part:"fruit"},
    {name: "blueberry", color: "blue", type:"fruit", eaten:"raw", part:"fruit"},
    {name: "broccoli", color: "green", type:"vegetable", eaten:"cooked or raw", part:"flower"},
    {name: "cauliflower", color: "white", type:"vegetable", eaten:"cooked or raw", part:"flower"},
    {name: "cucumber", color: "green", type:"vegetable", eaten:"raw", part:"fruit"},
    {name: "eggplant", color: "purple", type:"vegetable", eaten:"cooked", part:"fruit"},
    {name: "kiwi", color: "brown", type:"fruit", eaten:"raw", part:"fruit"},
    {name: "mango", color: "orange", type:"fruit", eaten:"raw", part:"fruit"},
    {name: "peach", color: "orange", type:"fruit", eaten:"raw", part:"fruit"},
    {name: "pear", color: "green", type:"fruit", eaten:"raw", part:"fruit"},
    {name: "pepper", color: "red", type:"vegetable", eaten:"cooked or raw", part:"fruit"},
    {name: "pumpkin", color: "orange", type:"vegetable", eaten:"cooked", part:"fruit"},
    {name: "tomato", color: "red", type:"fruit", eaten:"cooked or raw", part:"fruit"},
    {name: "watermelon", color: "red", type:"fruit", eaten:"raw", part:"fruit"},
    {name: "zucchini", color: "green", type:"vegetable", eaten:"cooked or raw", part:"fruit"},
    {name: "avocado", color: "green", type:"fruit", eaten:"raw", part:"fruit"},
    {name: "cherry", color: "red", type:"fruit", eaten:"raw", part:"fruit"},
    {name: "fig", color: "purple", type:"fruit", eaten:"raw", part:"fruit"},
    {name: "lemon", color: "yellow", type:"fruit", eaten:"raw", part:"fruit"},
    {name: "lime", color: "green", type:"fruit", eaten:"raw", part:"fruit"},
    {name: "orange", color: "orange", type:"fruit", eaten:"raw", part:"fruit"},
    {name: "pineapple", color: "yellow", type:"fruit", eaten:"raw", part:"fruit"},
    {name: "raspberry", color: "red", type:"fruit", eaten:"raw", part:"fruit"},
    {name: "blackberry", color: "black", type:"fruit", eaten:"raw", part:"fruit"},
    {name: "cranberry", color: "red", type:"fruit", eaten:"cooked or raw", part:"fruit"},
    {name: "grapefruit", color: "pink", type:"fruit", eaten:"raw", part:"fruit"},
    {name: "pomegranate", color: "red", type:"fruit", eaten:"raw", part:"fruit"},
    {name: "apricot", color: "orange", type:"fruit", eaten:"raw", part:"fruit"},
    {name: "nectarine", color: "orange", type:"fruit", eaten:"raw", part:"fruit"},
    {name: "plum", color: "purple", type:"fruit", eaten:"raw", part:"fruit"},
    {name: "melon", color: "green", type:"fruit", eaten:"raw", part:"fruit"},
    {name: "tangerine", color: "orange", type:"fruit", eaten:"raw", part:"fruit"},
    {name: "papaya", color: "orange", type:"fruit", eaten:"raw", part:"fruit"},
    {name: "coconut", color: "brown", type:"fruit", eaten:"raw", part:"fruit"},
    {name: "date", color: "brown", type:"fruit", eaten:"raw", part:"fruit"},

]